<?php
/* This file was generated by the install process. You can edit it. Please see config.original.php to understand the configuration items. */
$cfg = array (
  'web_root' => '62.72.23.119:8082/',
  'var_root' => '/jirafeau/var-2VyJXc1TMgnDnsI/',
  'lang' => 'auto',
  'style' => 'courgette',
  'dark_style' => 'dark-courgette',
  'organisation' => 'ACME',
  'contactperson' => '',
  'title' => '',
  'preview' => true,
  'enable_crypt' => false,
  'link_name_length' => 8,
  'upload_password' => 
  array (
  ),
  'upload_ip' => 
  array (
  ),
  'upload_ip_nopassword' => 
  array (
  ),
  'admin_password' => '',
  'admin_http_auth_user' => '',
  'availabilities' => 
  array (
    'minute' => true,
    'hour' => true,
    'day' => true,
    'week' => true,
    'fortnight' => true,
    'month' => true,
    'quarter' => false,
    'year' => false,
    'none' => false,
  ),
  'availability_default' => 'month',
  'one_time_download' => true,
  'maximal_upload_size' => 0,
  'proxy_ip' => 
  array (
  ),
  'file_hash' => 'random',
  'litespeed_workaround' => false,
  'use_xsendfile' => false,
  'store_uploader_ip' => true,
  'installation_done' => true,
  'debug' => false,
  'max_upload_chunk_size_bytes' => 100000000,
);